### ISSUE TITLE
inconsistency in the interface between from TheoryP2 and TheoryTemperature functions

### ISSUE THREAD

**Issue by giuspugl** [javicarron/pynkowski#1]
There's currently an inconsistency in the way 
`TheoryP2` is initialized 
https://github.com/javicarron/pynkowski/blob/26fa265b6d7634199a76c7189050c9ec9031ed60/pynkowski/theory/p2.py#L113 
wrt  `TheoryTemperature` 
https://github.com/javicarron/pynkowski/blob/26fa265b6d7634199a76c7189050c9ec9031ed60/pynkowski/theory/temperature.py#L110  

i suggest more internal   consistency  between  the two  interface .Ie: 

`mf.TheoryP2(us, Cls= cl   ) ` and `mf.TheoryTemperature(us, cls= cl)` . 

Moreover, 

when i call  
`theo, mu  = mf.TheoryP2(us, Cls= cl   ) ` 
i get the following error message : 
```---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-151-bf0c8dc5f467> in <module>
      1 #theo = mf.TheoryTemperature(us, cls=(input_cl[0] *(1-fl )*fl2 )  )
----> 2 theo, mu  = mf.TheoryP2(us, Cls=(input_cl[1:3] *(1-fl )*fl2 )  )

~/miniconda/envs/compsep/lib/python3.9/site-packages/pynkowski/theory/p2.py in __init__(self, us, Cls, μ, average_bin, edges)
    134         if (Cls is not None) and (μ is None):
    135             if (Cls.ndim == 2) and (Cls.shape[0]==2):
--> 136                 cls = (cls[0]+cls[1])/2.
    137             elif (Cls.ndim == 1):
    138                 cls = cls/2.

UnboundLocalError: local variable 'cls' referenced before assignment
```

**Comment by javicarron** [comment]
Thanks for the comment, #2 should fix this issue, it is implemented in version 0.2.3. :+1:
